# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def commonPods
  use_frameworks!
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxRelay', '6.1.0'
  pod 'IGListKit', '~> 4.0.0'
  pod 'AgoraRtcEngine_iOS',  :path => 'AgoraRtcEngine_iOS/AgoraRtcEngine_iOS.podspec'
end

target 'Core' do
  commonPods
  use_frameworks!
end

target 'InteractivePodcast' do
  commonPods
  use_frameworks!
  
end

target 'BlindDate' do
  commonPods
  use_frameworks!
  pod 'AgoraRtm_iOS'
end

target 'LivePKCore' do
  commonPods
  use_frameworks!
  pod 'AgoraMediaPlayer_iOS'
  pod 'AgoraRtm_iOS'
  pod 'AgoraLog'
  pod 'Toast-Swift'
end

target 'LiveMutiCore' do
  commonPods
  use_frameworks!
  pod 'AgoraLog'
  pod 'Toast-Swift'
end

target 'SuperAppCore' do
  commonPods
  use_frameworks!
  pod 'AgoraLog'
  pod 'Toast-Swift'
  pod 'Presentr'
  pod 'SyncManager', :path => '~/Agora/syncmanager/iOS/RtmSyncManager/SyncManager.podspec'
end

# target with leancloud sdk
target 'Scene-Examples_LeanCloud' do
  commonPods
  use_frameworks!
  pod 'LeanCloud', "17.10.0"
end

# target with firebase sdk
target 'Scene-Examples_Firebase' do
  commonPods
  use_frameworks!
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
end
