# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Scene-Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AgoraRtcEngine_iOS', :path => 'sdk/rtc/AgoraRtcEngine_iOS.podspec'
#  pod 'AgoraRtcEngine_Special_iOS', '3.6.213'
  pod 'AgoraScreenShare', :path => 'sdk'
  pod 'AgoraUIKit-iOS', '~> 1.0.0'
  pod 'AgoraSyncManager', '1.0.2'

end

